nome=input('Digite seu Nome:\n ').upper()
print('Olá',nome, 'Você é benvindo!! \nPreciso de informações para calcular seu IMC,\nPor favor utilize PONTO e não vírgula')
peso=float(input('  Qual seu Peso? \n'))
altura=float(input('  Qual sua altura?\n'))
resultado=(peso/(altura*altura))
print()
print('Uauuu!! {} Seu ICM é: {}, nada mau'.format(nome, resultado))