nome=input('Digite seu Nome:\n ').upper()
print('Olá',nome, 'Você é benvindo!! \nPreciso de informações para calcular seu IMC,\nPor favor utilize PONTO e não vírgula')
peso=float(input('  Qual seu Peso? \n'))
altura=float(input('  Qual sua altura?\n'))
resultado=(peso/(altura*altura))
print('{:.2f}'.format(resultado))
print(f'Uauuu!! {nome} Seu ICM é: {resultado:.2f}, nada mau!!!!!')